module.exports = {

  "com": ``,
  "net": ``,
  "org": `organization, organisation, nonprofit, charity, faith, church, mosque, program, education, give, love, Catholic, Islam, temple,synagogue, religion, Jewish, cause, activism`,
  "co": `business, firm, agency, biz, money, market, sell, buy, stocks, invest, wholesale, yen, ren, yuan, peso, company, corp, corporation, retail, manufacture, industry, supplier, entrepreneur, enterprises, operation, venture, capital, partnership, incorporated, workplace, work, profit, enterprise, monopoly `,

    "info": `fyi,information,data, facts`,
    "biz": `business, wholesale, buy, sell, market, stocks, investment, money, business, firm, agency, biz, money, market, sell, buy, stocks, invest, wholesale, yen, ren, yuan, peso, company, corp, corporation, retail, manufacture, industry, supplier, entrepreneur, enterprises, operation, venture, capital, partnership, incorporated, workplace, work, profit, enterprise, monopoly`,
    "mobi": `mobile, phone, call`,
    "name": `nombre, brand, monicker, nickname, surname`,
    "tel": `phone, telephone, talk, communicate, text, personal, information, `,
    "asia": `asian, china, india, chinese, indian, japan, japanese, korea, korean`,
    "travel": `adventure, explore, fly, plane, journey, cruise, voyage, trip, trek, safari`,
    "museum": `curate, exhibit, art, show, gallery, display, archive`,
    "edu": `school, education, learn, classes, study, teach, university`,
    "xxx": `sex, porn, pornography`,
    "post": `note, write, social,`,

  "app": `mobile, game, publish, ios, android, mac, windows,`,
  "ai": `tech, venture, science, automate, automatic, automated, artificial intelligence, nlp, artificial insemination, investment, smart, brain, learning, `,
  "io": `tech, startup, service, saas, on, off`,

  "pro": `professional, expert, specialist, skilled, master`,
  "inc": `llc, company, business, law, shop, boutique, `,
  "llc": `biz, business, corp, corporation`,
  "ltd": `inc, biz, business, corporation, registered, `,

  "am": `talk radio, media, audio, broadcast, news, listen, `,
  "fm": `radio, media, audio, broadcast, listen, music, song, dance, performance, `,
  "top": `best, mountain, excellent, great, shirt, blouse `,
  "icu": `see, you, me,`,
  "xyz": `abc, etc, algebra, math`,
  "vip": `bar, club, party, dance, disco, drinks, cocktails, mixology, limo, important, fancy, event `,
  "fun": `vacation, rv, kid, children, enjoy, laugh, comedy, happy, family`,
  "ooo": `music, art, dance, theater, literature, `,
  "win": `casino, winning, winnings, jackpot, money, cash, gold, `,
  "xin": `china, international, trade, import, export`,
  "one": `best, top, most, quality, genius, lucky, first `,
  "nyc": `city, usa, fintech, art, international, `,
  "art": `fine art, fine, craft, literature, music, theater, performance, life, painting, home, decoration, `,
  "ovh": ``,
  "fit": `fitness, health, exercise, gym, yoga, running, sport, diet, healthy, young, youth, `,
  "men": `shaving, gym, sports, whiskey, beer, women, sex, boy, kids, family, erection, health, doctor, medicine, `,
  "ink": `lit, writing, literature, magazine, news, media, multimedia, publish, `,
  "bid": `win, ecommerce, sales, business, investing, investment, buy, takeover, attempt, try, `,
  "pub": `bar, beer, ale, lager, night, going out, cafe, brew, brewery, restaurant, grub, food, library, publish, publication, book, article, magazine, literary, write, distribute, record,`,
  "red": `pink, orange, ruby, velvet, fashion, lipstick, blood, hospital, clinic, hot, alarm, alert`,
  "bet": `casino, winning, winnings, jackpot, money, cash, gold, black, gamble, las vegas `,
  "ren": `china, Chinese, money, currency, Asia, business`,
  "nrw": ``,
  "run": `athlete, healthy, lifestyle, life, workout, politics, program, candidate,`,
  "bio": `biology, documentary, history, life, historian, historical figure, important person, president, founder, war, science, anatomy, human, organism, medical, physio, eye, arm, leg, foot, toe, heel, finger, heart, liver, kidney, spine, bone, skin, muscle, joint, penis, vagina, sex, `,
  "uno": `one, self, best, mexico, spanish, now, `,
  "wtf": `omg, wow, crazy`,
  "kim": `kardashian, Korea, Korean `,
  "fyi": `info, your, my, about, nonsense, `,
  "frl": ``,
  "dog": `pet, vet, cat, dog food, pet food, kibble, spayed, neutered, husky, poodle, pomeranian, shiba inu, labrador, pg, beagle, bulldog, chihuahua, chow chow, terrier, maltese, boxer, rottweiler, retriever, doberman, shih tzu, great dane, `,
  "law": `legal, lawyer, judge, accountant, litigation, court, case, document, agreement, contract, business, property, signed, sign, jd, llm, jury`,
  "pet": `dog food, pet food, kibble, spayed, neutered, cat, dog, fish, turtle, bird, parrot, parakeet, creature, animal, lizard, loved, care, snake, llama, goat, horse, pony, feline, canine, furry `,
  "cat": `animal, feline, cute, furry, `,
  "eus": ``,
  "ist": ``,
  "lol": `haha, laugh, hahaha, ha, hohoho, funny, comedy, drama, teen, tween, game, entertainment, cheer, `,
  "bzh": ``,
  "moe": ``,
  "sex": `xxx, club, gentlemen, gay, intimate, romantic, fuck, fucking, tinder, dating, `,
  "cam": `video, vid, movie, production, editing, camera, hollywood, studio, drama, photo, photography, `,
  "tax": `accounting, lawyer, irs, government, city, state, fed, federal, `,
  "vet": `cat, dog, fish, horse, pony, bird, zoo, animal, hospital, pet `,
  "bar": `beer, ale, lager, night, going out, cafe, brew, brewery, restaurant, grub, food, `,
  "srl": ``,
  "vin": `wine, France, Napa, valley, rose, juice, grapes, vineyard, `,
  "onl": `online, web, IT, ecommerce, shop, boutique, store, kiosk, sale, merchant, `,
  "ski": `snow, fun, snowboard, skiing, snowboarding, resort, winter, xc, downhill, epic, rad, gnar, jump, `,
  "gal": `girl, woman, lady, miss, mrs, ms., feminine, makeup, lipstick, beauty, fashion, pretty, looking, strong, equal, mom, wine, `,
  "lat": `geo, globe, global, `,
  "eco": `trade, commerce, world, global, globalization, pollution, environmentalism, environment, nature, clean, new, pure, fresh, organic, alive, raw, `,
  "rip": `death, dead, funeral, last, end, tear, torn, broken, damaged, `,
  "fan": `popular, fanatic, concert, merch, `,
  "ong": ``,
  "ngo": `government, organization, `,
  "cab": ``,
  "mba": `business, degree, school, administration, biz, admin, manager, supervise,`,
  "ceo": `leader, business, money, company, cto, finance, admin, `,
  "how": `why, wiki, fyi, information, manual `,
  "mom": `woman, lady, mrs., ms., mama, mother `,
  "soy": `vegan, veggie, vegetarian, plant,`,
  "bot": `spider, crawl, robot, aggregate, automate, automatic, AI, artificial, intelligence, info, data, meta, `,
  "gop": `republican, conservative, news, Trump `,
  "rio": `grande, river, Mexico, spanish`,
  "krd": ``,
  "hiv": `red, aids, virus`,
  "car": `automobile, auto, transportation, go, drive, race, ford, nissan, hyundai, toyota, sports`,
  "moi": `me, myself, I, french`,
  "рус": ``,
  "орг": ``,
  "jobs": ``,
  "aero": ``,
  "coop": ``,
  "site": ``,
  "club": ``,
  "shop": ``,
  "work": ``,
  "live": ``,
  "tech": ``,
  "life": ``,
  "blog": ``,
  "buzz": ``,
  "host": ``,
  "wang": ``,
  "link": ``,
  "news": ``,
  "guru": ``,
  "best": ``,
  "loan": ``,
  "love": ``,
  "tips": ``,
  "city": ``,
  "zone": ``,
  "team": ``,
  "care": ``,
  "sale": ``,
  "gmbh": ``,
  "wiki": ``,
  "cool": ``,
  "date": ``,
  "farm": ``,
  "land": ``,
  "casa": ``,
  "bike": ``,
  "cafe": ``,
  "immo": ``,
  "wien": ``,
  "fund": ``,
  "plus": ``,
  "blue": ``,
  "kiwi": ``,
  "wine": ``,
  "beer": ``,
  "help": ``,
  "band": ``,
  "cash": ``,
  "chat": ``,
  "scot": ``,
  "yoga": ``,
  "show": ``,
  "porn": ``,
  "golf": ``,
  "ruhr": ``,
  "pink": ``,
  "gold": ``,
  "sexy": ``,
  "pics": ``,
  "luxe": ``,
  "taxi": ``,
  "camp": ``,
  "haus": ``,
  "gift": ``,
  "menu": ``,
  "surf": ``,
  "toys": ``,
  "fish": ``,
  "rent": ``,
  "film": ``,
  "town": ``,
  "desi": ``,
  "fail": ``,
  "gent": ``,
  "tube": ``,
  "moda": ``,
  "vote": ``,
  "bank": ``,
  "lgbt": ``,
  "game": ``,
  "army": ``,
  "rest": ``,
  "limo": ``,
  "diet": ``,
  "baby": ``,
  "fans": ``,
  "sarl": ``,
  "navy": ``,
  "reit": ``,
  "ltda": ``,
  "qpon": ``,
  "auto": ``,
  "voto": ``,
  "cars": ``,
  "rich": ``,
  "сайт": ``,
  "дети": ``,
  "space": ``,
  "store": ``,
  "cloud": ``,
  "world": ``,
  "tokyo": ``,
  "rocks": ``,
  "today": ``,
  "email": ``,
  "group": ``,
  "media": ``,
  "click": ``,
  "trade": ``,
  "press": ``,
  "ninja": ``,
  "koeln": ``,
  "party": ``,
  "paris": ``,
  "video": ``,
  "works": ``,
  "photo": ``,
  "house": ``,
  "games": ``,
  "swiss": ``,
  "guide": ``,
  "earth": ``,
  "coach": ``,
  "vegas": ``,
  "legal": ``,
  "wales": ``,
  "tools": ``,
  "style": ``,
  "money": ``,
  "homes": ``,
  "tours": ``,
  "codes": ``,
  "watch": ``,
  "miami": ``,
  "sport": ``,
  "deals": ``,
  "adult": ``,
  "jetzt": ``,
  "dance": ``,
  "sucks": ``,
  "cymru": ``,
  "pizza": ``,
  "tirol": ``,
  "solar": ``,
  "promo": ``,
  "faith": ``,
  "parts": ``,
  "cards": ``,
  "audio": ``,
  "green": ``,
  "shoes": ``,
  "black": ``,
  "irish": ``,
  "loans": ``,
  "place": ``,
  "build": ``,
  "cheap": ``,
  "gifts": ``,
  "glass": ``,
  "poker": ``,
  "movie": ``,
  "salon": ``,
  "horse": ``,
  "archi": ``,
  "radio": ``,
  "actor": ``,
  "vodka": ``,
  "lease": ``,
  "gives": ``,
  "rehab": ``,
  "bible": ``,
  "study": ``,
  "bingo": ``,
  "gripe": ``,
  "reise": ``,
  "tires": ``,
  "tatar": ``,
  "kyoto": ``,
  "osaka": ``,
  "rodeo": ``,
  "rugby": ``,
  "boats": ``,
  "autos": ``,
  "forex": ``,
  "lotto": ``,
  "online": ``,
  "design": ``,
  "agency": ``,
  "studio": ``,
  "global": ``,
  "london": ``,
  "berlin": ``,
  "center": ``,
  "expert": ``,
  "bayern": ``,
  "events": ``,
  "church": ``,
  "social": ``,
  "market": ``,
  "africa": ``,
  "stream": ``,
  "photos": ``,
  "family": ``,
  "moscow": ``,
  "coffee": ``,
  "review": ``,
  "webcam": ``,
  "school": ``,
  "boston": ``,
  "direct": ``,
  "energy": ``,
  "health": ``,
  "lawyer": ``,
  "estate": ``,
  "clinic": ``,
  "sydney": ``,
  "dental": ``,
  "tattoo": ``,
  "racing": ``,
  "report": ``,
  "vision": ``,
  "repair": ``,
  "quebec": ``,
  "kaufen": ``,
  "nagoya": ``,
  "doctor": ``,
  "casino": ``,
  "supply": ``,
  "credit": ``,
  "insure": ``,
  "reisen": ``,
  "gratis": ``,
  "camera": ``,
  "joburg": ``,
  "dating": ``,
  "soccer": ``,
  "schule": ``,
  "claims": ``,
  "degree": ``,
  "voyage": ``,
  "garden": ``,
  "futbol": ``,
  "durban": ``,
  "realty": ``,
  "taipei": ``,
  "alsace": ``,
  "tienda": ``,
  "condos": ``,
  "villas": ``,
  "ryukyu": ``,
  "tennis": ``,
  "hockey": ``,
  "viajes": ``,
  "career": ``,
  "physio": ``,
  "maison": ``,
  "luxury": ``,
  "hiphop": ``,
  "broker": ``,
  "juegos": ``,
  "voting": ``,
  "madrid": ``,
  "yachts": ``,
  "makeup": ``,
  "москва": ``,
  "онлайн": ``,
  "website": ``,
  "company": ``,
  "network": ``,
  "digital": ``,
  "realtor": ``,
  "academy": ``,
  "systems": ``,
  "support": ``,
  "wedding": ``,
  "hamburg": ``,
  "reviews": ``,
  "gallery": ``,
  "science": ``,
  "capital": ``,
  "rentals": ``,
  "fitness": ``,
  "cologne": ``,
  "fashion": ``,
  "finance": ``,
  "careers": ``,
  "express": ``,
  "kitchen": ``,
  "domains": ``,
  "forsale": ``,
  "recipes": ``,
  "okinawa": ``,
  "limited": ``,
  "holiday": ``,
  "auction": ``,
  "hosting": ``,
  "college": ``,
  "singles": ``,
  "dentist": ``,
  "jewelry": ``,
  "exposed": ``,
  "coupons": ``,
  "flights": ``,
  "cricket": ``,
  "cruises": ``,
  "florist": ``,
  "charity": ``,
  "organic": ``,
  "courses": ``,
  "surgery": ``,
  "cooking": ``,
  "corsica": ``,
  "fishing": ``,
  "flowers": ``,
  "theater": ``,
  "trading": ``,
  "shiksha": ``,
  "guitars": ``,
  "country": ``,
  "tickets": ``,
  "markets": ``,
  "storage": ``,
  "abogado": ``,
  "hoteles": ``,
  "whoswho": ``,
  "theatre": ``,
  "services": ``,
  "business": ``,
  "training": ``,
  "software": ``,
  "download": ``,
  "ventures": ``,
  "clothing": ``,
  "exchange": ``,
  "istanbul": ``,
  "boutique": ``,
  "pictures": ``,
  "partners": ``,
  "brussels": ``,
  "attorney": ``,
  "graphics": ``,
  "shopping": ``,
  "delivery": ``,
  "lighting": ``,
  "holdings": ``,
  "computer": ``,
  "capetown": ``,
  "football": ``,
  "yokohama": ``,
  "discount": ``,
  "saarland": ``,
  "builders": ``,
  "catering": ``,
  "engineer": ``,
  "property": ``,
  "mortgage": ``,
  "supplies": ``,
  "bargains": ``,
  "plumbing": ``,
  "diamonds": ``,
  "cleaning": ``,
  "feedback": ``,
  "hospital": ``,
  "democrat": ``,
  "observer": ``,
  "memorial": ``,
  "abudhabi": ``,
  "airforce": ``,
  "pharmacy": ``,
  "security": ``,
  "broadway": ``,
  "solutions": ``,
  "amsterdam": ``,
  "education": ``,
  "marketing": ``,
  "directory": ``,
  "community": ``,
  "institute": ``,
  "melbourne": ``,
  "barcelona": ``,
  "financial": ``,
  "equipment": ``,
  "vacations": ``,
  "furniture": ``,
  "christmas": ``,
  "insurance": ``,
  "stockholm": ``,
  "technology": ``,
  "consulting": ``,
  "foundation": ``,
  "properties": ``,
  "management": ``,
  "healthcare": ``,
  "restaurant": ``,
  "university": ``,
  "immobilien": ``,
  "vlaanderen": ``,
  "accountant": ``,
  "industries": ``,
  "apartments": ``,
  "associates": ``,
  "creditcard": ``,
  "republican": ``,
  "protection": ``,
  "photography": ``,
  "productions": ``,
  "engineering": ``,
  "enterprises": ``,
  "investments": ``,
  "contractors": ``,
  "accountants": ``,
  "blackfriday": ``,
  "creditunion": ``,
  "motorcycles": ``,
  "construction": ``,
  "versicherung": ``,
  "international": ``,
  "网址": ``,
  "在线": ``,
  "公司": ``,
  "手机": ``,
  "商标": ``,
  "网络": ``,
  "商城": ``,
  "我爱你": ``,
  "中文网": ``,
  "닷컴": ``,
  "网店": ``,
  "コム": ``,
  "移动": ``,
  "קום": ``,
  "信息": ``,
  "集团": ``,
  "购物": ``,
  "企业": ``,
  "닷넷": ``,
  "みんな": ``,
  "世界": ``,
  "شبكة": ``,
  "商店": ``,
  "بازار": ``,
  "网站": ``,
  "موقع": ``,
  "机构": ``,
  "游戏": ``,
  "ストア": ``,
  "广东": ``,
  "娱乐": ``,
  "セール": ``,
  "招聘": ``,
  "佛山": ``,
  "संगठन": ``,
  "餐厅": ``,
  "家電": ``,
  "クラウド": ``,
  "食品": ``,
  "八卦": ``,
  "書籍": ``,
  "ac": `academic, academy`,
  "ad": `advert, marketing, agency, `,
  "ag": `agriculture, farm, harvest, german`, // germany's llc or inc equivalent: "aktiengesellschaft"
  "as": `estonia`, // estonia's llc or inc equivalent: "akciová společnost"; as {preposition}, as a {noun}, as {adverb}
  "at": ``,
  "be": `become`, // youtu.be
  "by": ``, // fly {by}
  "cc": `christian, christ, jesus, church, college, community college, community`,
  "cd": `cd, music, tunes, listen, `,
  "ch": `church, jesus, christian, christ, `,
  "ck": ``,
  "dj": `dj, club, music, clubbing, party, `,
  "es": ``, // beach{es}
  "fi": `hifi, audio, recording, `,
  "gl": `galic, galicia, greenland, google`,
  "gg": `gaming, gambling, poker, casino, `,
  "im": `instant messaging, texting, text, sms, chat, online, `,
  "is": ``, // is {adj/adv}
  "ir": `iran`,
  "it": `italy, do, act, `, // {verb} it
  "je": `dutch, french, jersey, i, `,
  "la": `los angeles, latin, `,
  "li": `long island`,
  "lv": `love`,
  "ly": ``, // {noun/adj}ly
  "md": `doctor, medical, medicine, hospital, nursing, medschool, mcat, `,
  "me": `montenegro, middle east, `,
  "mn": `mongolia, minnesota, `,
  "ms": `microsoft`,
  "mu": `music, song, musical, playing, acoustic, vocal, rock, pop music, rap, performance art, `,
  "ni": ``,
  "nu": `new, nude`,
  "pr": `public relations, marketing, human resources, press release, press`,
  "rs": ``, // {blogge}rs
  "sc": `source`,
  "sh": `china`,
  "si": `slovenia, yes`,
  "sr": `senior, old, respectable, `,
  "st": `street`,
  "tc": `turk`,
  "tm": `trademark, copyright, slogan, trade, mark, logo, `,
  "to": `toronto, turino, `, //
  "tv": `television, italy`,
  "vc": `venture capital, vacation, casino, `,
  "vg": `video games, `,
  "vu": `view`,
  "ws": `website`,
  "in": `india, internet, `, // {noun} in

  "ca": `canada, california, `,
  "ae": ``,
  "af": ``,
  "al": ``,
  "ao": ``,
  "aq": ``,
  "ar": ``,
  "au": ``,
  "aw": ``,
  "ax": ``,
  "az": ``,
  "ba": ``,
  "bb": ``,
  "bd": ``,
  "bf": ``,
  "bg": ``,
  "bh": ``,
  "bi": ``,
  "bj": ``,
  "bm": ``,
  "bn": ``,
  "bo": ``,
  "br": ``,
  "bs": ``,
  "bt": ``,
  "bv": ``,
  "bw": ``,
  "bz": ``,
  "cf": ``,
  "cg": ``,
  "ci": ``,
  "cl": ``,
  "cm": ``,
  "cn": ``,
  "cr": ``,
  "cu": ``,
  "cv": ``,
  "cw": ``,
  "cx": ``,
  "cy": ``,
  "cz": ``,
  "de": ``,
  "dk": ``,
  "dm": ``,
  "do": ``,
  "dz": ``,
  "ec": ``,
  "ee": ``,
  "eg": ``,
  "er": ``,
  "et": ``,
  "eu": ``,
  "fj": ``,
  "fk": ``,
  "fo": ``,
  "fr": ``,
  "ga": ``,
  "gb": ``,
  "gd": ``,
  "ge": ``,
  "gf": ``,
  "gh": ``,
  "gi": ``,
  "gm": ``,
  "gn": ``,
  "gp": ``,
  "gq": ``,
  "gr": ``,
  "gs": ``,
  "gt": ``,
  "gu": ``,
  "gw": ``,
  "gy": ``,
  "hk": ``,
  "hm": ``,
  "hn": ``,
  "hr": ``,
  "ht": ``,
  "hu": ``,
  "id": ``,
  "ie": ``,
  "il": ``,
  "iq": ``,
  "jm": ``,
  "jo": ``,
  "jp": ``,
  "ke": ``,
  "kg": ``,
  "kh": ``,
  "ki": ``,
  "km": ``,
  "kn": ``,
  "kp": ``,
  "kr": ``,
  "kw": ``,
  "ky": ``,
  "kz": ``,
  "lb": ``,
  "lc": ``,
  "lk": ``,
  "lr": ``,
  "ls": ``,
  "lt": ``,
  "lu": ``,
  "ma": ``,
  "mc": ``,
  "mg": ``,
  "mh": ``,
  "mk": ``,
  "ml": ``,
  "mm": ``,
  "mo": ``,
  "mp": ``,
  "mq": ``,
  "mr": ``,
  "mt": ``,
  "mv": ``,
  "mw": ``,
  "mx": ``,
  "my": ``,
  "mz": ``,
  "na": ``,
  "nc": ``,
  "ne": ``,
  "nf": ``,
  "ng": ``,
  "nl": ``,
  "no": ``,
  "np": ``,
  "nr": ``,
  "nz": ``,
  "om": ``,
  "pa": ``,
  "pe": ``,
  "pf": ``,
  "pg": ``,
  "ph": ``,
  "pk": ``,
  "pl": ``,
  "pm": ``,
  "pn": ``,
  "ps": ``,
  "pt": ``,
  "pw": ``,
  "py": ``,
  "qa": ``,
  "re": ``,
  "ro": ``,
  "ru": ``,
  "rw": ``,
  "sa": ``,
  "sb": ``,
  "sd": ``,
  "se": ``,
  "sg": ``,
  "sj": ``,
  "sk": ``,
  "sl": ``,
  "sm": ``,
  "sn": ``,
  "so": ``,
  "ss": ``,
  "su": ``,
  "sv": ``,
  "sx": ``,
  "sy": ``,
  "sz": ``,
  "td": ``,
  "tf": ``,
  "tg": ``,
  "th": ``,
  "tj": ``,
  "tk": ``,
  "tl": ``,
  "tn": ``,
  "tr": ``,
  "tt": ``,
  "tw": ``,
  "tz": ``,
  "ua": ``,
  "ug": ``,
  "uk": ``,
  "us": ``,
  "uy": ``,
  "uz": ``,
  "va": ``,
  "ve": ``,
  "vi": ``,
  "vn": ``,
  "wf": ``,
  "ye": ``,
  "yt": ``,
  "za": ``,
  "zm": ``,
  "zw": ``,


  "gdn": ``,

};
