module.exports = {

  "com": ``,
  "net": `web, electronic, science, communicate, together, channel, build, link, access, transmit, train, operate, design, learn, share, connect, internet, interconnect, organization, systems, online, cyber, site, website, signal, talk, speech, connectivity,, nexus, plexus, animation, local, distant, call, phone, global, worldwide, integrated, digital, tech, artificial, intelligence, distributed, center, hybrid, country, media, multimedia, game, gaming, art, create, computer, pc, laptop`,
  "org": `children, women, organization, gift, school, learn, share, contribute, public, compassion, holy, pure, kind, gala, good, volunteer, Christian, Christ, Jesus, donator,humane, kindness, mercy, people, love, orphan, fundraise, philanthropy, global, international, donation, foundation, benefit, fund, welfare, organisation, nonprofit, charity, faith, church, mosque, program, education, give, love, Catholic, Islam, temple,synagogue, religion, Jewish, cause, activism`,
  "co": `tech, startups, business, firm, agency, biz, money, design, market, sell, buy, stocks, invest, wholesale, yen, ren, yuan, peso, company, corp, consultant, corporation, retail, manufacture, industry, supplier, entrepreneur, enterprises, jobs, labor, employee, employer, occupation, operation, venture, capital, partnership, incorporated, workplace, work, profit, enterprise, monopoly `,

  "info": `fyi, notify, provide, process, verify, obtain, science, transfer, journalism, write, media, press, clarify, intel, site, information, data, facts, network, document, knowledge, database, evidence, tips, resources, statistics, stats, math, insigh, feedback, material, update, advice, news, intelligence, services, description, records, communications, report, tech, technology, site, content, input, messages, explanation, explain, understand, education, educate, school, university, public, psa, file, guide, know, brief, investigation, electronic, computer, advise, enquiries`,
  "biz": `revenue, marketing, business, economy, bank, imports, startups, promotional, advertise, agency, wholesale, buy, sell, market, stocks, investment, money, business, consultant, firm, agency, biz, money, market, sell, buy, stocks, invest, wholesale, yen, ren, yuan, peso, company, corp, corporation, retail, manufacture, industry, supplier, entrepreneur, enterprises, operation, venture, capital, partnership, incorporated, workplace, work, profit, enterprise, monopoly`,
  "mobi": `mobile, phone, call`,
  "name": `nombre, first, last, nominate, appoint, call, brand, monicker, nickname, surname, pseudonym, username, identification, person, identity, brand, profile,`,
  "tel": `phone, telephone, talk, communicate, text, personal, information, electronic `,
  "asia": `asian, china, india, chinese, indian, japan, japanese, korea, korean, nipponese`,
  "travel": `holiday, fun, hotel, language, overseas, planet, south, west, north, east, abroad, Europe, Africa, Asia, Australia, Antartica, Mexico, America, Canada, ocean, luxury, hostel, bed, breakfast, fun, foreign, culture, new, international, world, cruise, ride, navigation, exotic, sail, car, road, gps, visit, go, move, tourism, ticket, flight, destination, vacation, visa, honeymoon,adventure, explore, fly, plane, journey, cruise, voyage, trip, trek, safari`,
  "museum": `culture, children, tour, anthropological, science, ethnographic, natural, visit,curate, library, collections, heritage, conservatory, national, archeology, statue, garden, paintings, park, archives, paleontology, history, relics, treasure, zoo, botany, venue, exhibit, art, show, gallery, display, archive`,
  "edu": `secondary, institution, primary, college, technical, intern, public, private, charter, apprenticeship, attendance,train, children, school, education, learn, classes, enroll, academic, academia, degree, tuition, diploma, research, scholar, advocacy, lessons, grade, knowledge, course,study, student, teacher, instruction, train, curriculum, educators, teach, university`,
  "xxx": `babe, steamy, slutty, panties, risque, lusty, foxy, naughty, lewd, seduce, kinky, topless, boobs, suck, flirt, sex, porn, pornography, arouse, erotic, shagging, booty, screw, fuck, horny, orgasm, hot, nasty, creamy, tight, curvy, sexy,`,
  "post": `note, write, office, mail, follow, account, media, social, brand, email, wall, send, letter, office`,

  "app": `mobile, applications, mobile, technical, intelligence, startups, gadgets, science, engineer, innovate, devices,frontend, backend, design, tech, web, electronics, text, game, publish, ios, android, io, ai, mac, windows, application, program, software, coding, code, python, javascript, html, css, sql, database, security, developer,  `,
  "ai": `tech, applications, mobile, intelligence, startups, innovate, gadgets, robotis, humanoid, nanotech, automation, venture, devices, engineer, science, automate, automatic, automated, artificial intelligence, nlp, artificial insemination, investment, smart, brain, learning, `,
  "io": `tech, applications, mobile, intelligence, gadgets, startups, science, innovate, engineering, entrepreneur, intelligence, artificial, robots, systems, devices computer, biotech, business, startup, service, saas, on, off, mobile, frontend, backend, design, tech, web, electronics, text, game, publish, ios, android, io, ai, mac, windows, application, program, software, coding, code, python, javascript, html, css, sql, database, security, developer,`,

  "pro": `professional, expert, specialist, skilled, master, business, internship, technology, tech, credentials, career, trained, coaching, specialized, occupation, vocation, work, employment, employee, consultant, employer, career, industry, admin, management, trades, jobs, labor, talent, prodigy, mentor,`,
  "inc": `llc, oragnization, company, business, law, shop, boutique, corporate, business, imports, startups, promotional, advertise, agency, wholesale, buy, sell, market, stocks, investment, money, business, consultant, firm, agency, biz, money, market, sell, buy, stocks, invest, wholesale, yen, ren, yuan, peso, company, corp, corporation, retail, manufacture, industry, supplier, entrepreneur, enterprises, operation, venture, capital, partnership, incorporated, workplace, work, profit, enterprise, monopoly`,
  "llc": `llc, oragnization, company, business, law, shop, boutique, corporate, business, imports, startups, promotional, advertise, agency, wholesale, buy, sell, market, stocks, investment, money, business, consultant, firm, agency, biz, money, market, sell, buy, stocks, invest, wholesale, yen, ren, yuan, peso, company, corp, corporation, retail, manufacture, industry, supplier, entrepreneur, enterprises, operation, venture, capital, partnership, incorporated, workplace, work, profit, enterprise, monopoly, biz, business, corp, corporation`,
  "ltd": `llc, oragnization, company, business, law, shop, boutique, corporate, business, imports, startups, promotional, advertise, agency, wholesale, buy, sell, market, stocks, investment, money, business, consultant, firm, agency, biz, money, market, sell, buy, stocks, invest, wholesale, yen, ren, yuan, peso, company, corp, corporation, retail, manufacture, industry, supplier, entrepreneur, enterprises, operation, venture, capital, partnership, incorporated, workplace, work, profit, enterprise, monopolyinc, biz, business, corporation, registered, `,

  "am": `talk radio, media, audio, broadcast, news, listen, `,
  "fm": `radio, media, audio, broadcast, listen, music, song, dance, performance, entertainment`,
  "top": `best, lead, trump, most, highest, ranking, awesome, boss, elite, apex, paramount, upper, prime, supreme, dominant, mountain, excellent, great, pinnacle, peak, transcend, max, first, exceed,  `,
  "icu": `see, you, me, intensive, medicine, medical, care,`,
  "xyz": `abc, etc, algebra, math, alphabet`,
  "vip": `bar, club, party, dance, disco, drinks, cocktails, mixology, limo, important, fancy, event `,
  "fun": `watch, frolic, kids, recreation, festival, gala, dance, party, wine, art, hobby, create, music, drinks, vocation, rv, kid, children, enjoy, laugh, comedy, happy, family, entertainment, play, sport, enjoy, funny, thrill, skydive, exciting, cute, pleasant, interesting, comical, cheerful, games, video, fantasy, delight, friends, happy, wholesome, holiday, outdoor, free, luxury, children,`,
  "ooo": `music, art, dance, theater, literature, interesting, fun, tech, love, yahoo, yipee, yes, weee, haha, lol, crazy, cute, japan, whoa, wohoo, nonsense, wild, golly, jeez, yeah `,
  "win": `medal, casino, winning, winnings, jackpot, money, cash, gold, great, success, gain, profits, victory, compete, champion, race, sport, ultimate, intense, prize, sweepstakes, election, campaign, lottery, contest `,
  "xin": `china, international, trade, import, export`,
  "one": `best, top, most, quality, genius, lucky, first `,
  "nyc": `city, usa, fintech, art, international `,
  "art": `fine art, fine, craft, literature, music, theater, performance, life, painting, home, decoration, `,
  "ovh": ``,
  "fit": `fitness, health, exercise, gym, yoga, running, sport, diet, healthy, young, youth, `,
  "men": `shaving, gym, sports, whiskey, beer, women, sex, boy, kids, family, erection, health, doctor, medicine, `,
  "ink": `lit, writing, literature, magazine, news, media, multimedia, publish, `,
  "bid": `win, ecommerce, sales, business, investing, investment, buy, takeover, attempt, try, `,
  "pub": `bar, beer, ale, lager, night, going out, cafe, brew, brewery, restaurant, grub, food, library, publish, publication, book, article, magazine, literary, write, distribute, record,`,
  "red": `pink, orange, ruby, velvet, fashion, lipstick, blood, hospital, clinic, hot, alarm, alert`,
  "bet": `casino, winning, winnings, jackpot, money, cash, gold, black, gamble, las vegas `,
  "ren": `china, Chinese, money, currency, Asia, economy, business`,
  "nrw": ``,
  "run": `athlete, healthy, lifestyle, life, workout, politics, program, candidate,`,
  "bio": `biology, documentary, history, life, historian, historical figure, important person, president, founder, war, science, anatomy, human, organism, medical, physio, eye, arm, leg, foot, toe, heel, finger, heart, liver, kidney, spine, bone, skin, muscle, joint, penis, vagina, sex, `,
  "uno": `one, self, best, mexico, spanish, now, `,
  "wtf": `omg, wow, crazy`,
  "kim": `kardashian, Korea, Korean `,
  "fyi": `info, your, my, about, nonsense, `,
  "frl": `real`,
  "dog": `pet, vet, cat, dog food, pet food, kibble, spayed, neutered, husky, poodle, pomeranian, shiba inu, labrador, pg, beagle, bulldog, chihuahua, chow chow, terrier, maltese, boxer, rottweiler, retriever, doberman, shih tzu, great dane, `,
  "law": `legal, lawyer, judge, accountant, litigation, court, case, document, agreement, contract, business, property, signed, sign, jd, llm, jury`,
  "pet": `dog food, pet food, kibble, spayed, neutered, cat, dog, fish, turtle, bird, parrot, parakeet, creature, animal, lizard, loved, care, snake, llama, goat, horse, pony, feline, canine, furry `,
  "cat": `animal, feline, cute, furry, `,
  "eus": ``,
  "ist": ``,
  "lol": `haha, laugh, hahaha, ha, hohoho, funny, comedy, drama, teen, tween, game, entertainment, cheer, `,
  "bzh": ``,
  "moe": ``,
  "sex": `xxx, club, gentlemen, gay, intimate, romantic, fuck, fucking, tinder`,
  "cam": `video, vid, movie, production, editing, camera, hollywood, studio, drama, photo, photography, `,
  "tax": `accounting, lawyer, irs, government, city, state, fed, federal, `,
  "vet": `cat, dog, fish, horse, pony, bird, zoo, animal, hospital, pet `,
  "bar": `beer, ale, lager, night, going out, cafe, brew, brewery, restaurant, grub, food, `,
  "srl": ``,
  "vin": `wine, France, Napa, valley, rose, juice, grapes, vineyard, `,
  "onl": `online, web, IT, ecommerce, shop, boutique, store, kiosk, sale, merchant, `,
  "ski": `snow, fun, snowboard, skiing, snowboarding, resort, winter, xc, downhill, epic, rad, gnar, jump, `,
  "gal": `girl, woman, lady, miss, mrs, ms., feminine, makeup, lipstick, beauty, fashion, pretty, looking, strong, equal, mom, wine, `,
  "lat": `geo, globe, global, `,
  "eco": `trade, commerce, world, global, globalization, pollution, environmentalism, environment, nature, clean, new, pure, fresh, organic, alive, raw, `,
  "rip": `death, dead, funeral, last, end, tear, torn, broken, damaged, `,
  "fan": `popular, fanatic, concert, merch, `,
  "ong": ``,
  "ngo": `government, organization, `,
  "cab": `taxi, uber, ride, transport, cabarnet`,
  "mba": `business, economy, degree, school, administration, biz, admin, manager, supervise,`,
  "ceo": `leader, business, money, company, cto, finance, admin, `,
  "how": `why, wiki, fyi, information, manual `,
  "mom": `woman, lady, mrs., ms., mama, mother `,
  "soy": `vegan, veggie, vegetarian, plant,`,
  "bot": `spider, crawl, robot, aggregate, automate, automatic, AI, artificial, intelligence, info, data, meta, `,
  "gop": `republican, conservative, news, Trump `,
  "rio": `grande, river, Mexico, spanish`,
  "krd": ``,
  "hiv": `red, aids, virus`,
  "car": `automobile, auto, transportation, go, drive, race, ford, nissan, hyundai, toyota, sports`,
  "moi": `me, myself, I, french, boutique, fancy, love`,
  "рус": ``,
  "орг": `operation`,
  "jobs": `work, career, profession, occupation, trade, vocation, employee, employer, search, boss`,
  "aero": `space, universe, nasa, aliens, astronauts, physics, fly, aviation, plane, circus, gymnastics`,
  "coop": `chicken, business, house, collaborate, together, union, partner, greens, contribute`,
  "site": `website, cyberspace, content, blog, spot, vlog, sell, location, land, navigation, online, page, station, operation, network, information, business`,
  "club": `trendy, event, sport, performance, show, comedy, singing, gig, band, stage, league, team, sorority, karaoke, party, fun, dancing, night, happy, society, association, guild, frat, gym, disco, member`,
  "shop": `store, buy, sell, market, clothes, customers, business, money, salon, studio, cafe, bakery`,
  "work": `job, projects, employee, search, excercise, union, labor, profession, career, occupation  `,
  "live": `happy, life, healthy, fitness, now, on, watch`,
  "tech": `applications, mobile, intelligence, gadgets, startups, science, innovate, engineering, entrepreneur, intelligence, artificial, robots, systems, devices computer, biotech, business, startup, service, saas, on, off, mobile, frontend, backend, design, tech, web, electronics, text, game, publish, ios, android, io, ai, mac, windows, application, program, software, coding, code, python, javascript, html, css, sql, database, security, developer,`,
  "life": `healthy, fresh, green, fitness, together, family, fun, safe,`,
  "blog": `write, post, content, vlog, influencer, influence, story, share, website, newsletter, wordpress, tweet, wiki, forum, post,`,
  "buzz": `feed, trendy, fun, game, thrill, excitement, kids, interesting, mania, crazy, vibe, suspense`,
  "host": `party, event, club, fun, computer, domain, show, DJ, performance `,
  "wang": `chicken, chinese, china, king`,
  "link": `website, document, content, connect, join, attach, plug, site, blog, search, find`,
  "news": `update, word, program, weather, world, media, press, journalism, reporter, bulletin, paper, bried, story, coverage, journalism,column, knowledge, information, journals, gazette`,
  "guru": `advice, consultant, professional, expert, specialist, skilled, master, business, internship, technology, tech, credentials, career, trained, coaching, specialized, occupation, vocation, work, employment, employee, consultant, employer, career, industry, admin, management, trades, jobs, labor, talent, prodigy, mentor,`,
  "best": `top, greatest, supreme, trump, champion, sport, hot, fast, healthy, fit, success, prize, win`,
  "loan": `interest, credit, money, bank, give, finance, invest, mortgage, len, payment, debt, fund, borrow, pay`,
  "love": `good, kind, marry, engage, couple, sweet, partner, bride, groom, relationship, beautiful, pretty, heart, pink, red, valentines, valentine, february, holiday, gift, give, hug, friends, husband, wife, god, allah, people, humans, children, family, life, healthy, `,
  "tips": `work, server, resource, fyi, information, consultation, how, wiki, help, ideas`,
  "city": `new york, chicago, los angeeles, mayor, town, cosmopolitan, villa, party, nyc, events, explore, travel, tech, fun, america, metro, urban, town, people, community, local, `,
  "zone": `fun, sport, event, party, area, study, space`,
  "team": `sports, together, frat, club, league, coach, game, division, mission, partner, business`,
  "care": `love, pet, family, children, kids, spouse, friends,`,
  "sale": `buy, business, money, sell, shop, customers, market, purchase, supply, retail, whoesale, marketing`,
  "gmbh": ``,
  "wiki": `information, learn, search, question, resource, reference`,
  "cool": `fun, interesting, trendy, awesome, stylish`,
  "date": `love, chocolates, calendar, event, wedding, cute, night, party,`,
  "farm": `green, healthy, life, animals, food, fresh, garden, vegetables, fruit, livestock`,
  "land": `invest, property, house, home, live, green, planet, world`,
  "casa": `house, home, land, property, mansion, place, event, family, love`,
  "bike": `ride, sport, fun, motorbike, motorcycle, electric`,
  "cafe": `shop, customers, bakery, coffee, cafeteria, food, meet, friends, relax,`,
  "immo": ``,
  "wien": ``,
  "fund": `money, hedge, economy, capital, business, invest, bank, savings, partner, pay, crowd, tech`,
  "plus": `add, with, and, together, coop, collab, collaborate, team, more, greatest, large, big, bbw`,
  "blue": `sky, kids, fun, clouds, fly, water, ocean, sail, boat, voyage, cruise, travel, trust, police, cops, sad`,
  "kiwi": `fruit, fun, zealand, sweet, coloful, cute, kids`,
  "wine": `vino, tasting, grape, vine, relax, luxury, romance, red, drink, alcohol, merlot, cabarnet, bottle,`,
  "beer": `fun, party, pong, flight, club, pub, event, drinks, lager, pint, alcohol, brews, draft`,
  "help": `give, counsel,assist, serve, aid, support, charity, faith, god, religion, christ, churhch, hunger, traffick, advice, patient, care, therapy, listen, call, police, alert, amber, red, medicine,`,
  "band": `music, love, together, gig, set, orchestra, crew, guitar, ensemble, dance, club, show, stage,`,
  "cash": `money, economy, interest, credit, bank, atm, fund, business, sell, buy, green`,
  "chat": `talk, text, communicate, ask, question, information, friend, cafe, news, gossip, update, conversation, media, social`,
  "scot": ``,
  "yoga": `peace, hatha, bikram, guru, flexibile, health, fitness, green, vegan, tantra, karma, mantra, india, buddha, natural, nature, yogi, mindfulness, mental, wellness, vinyasa, hot, lotus, relax, dance, pole, workout`,
  "show": `performance, comedy, event, music, happy, fun, watch, movie, cinema, exhibit, dance, ballet, entertainment, presentation, TV`,
  "porn": `xxx, club, intimate, romantic, fuck, fucking, tinder, smutty, orgy`,
  "golf": `sport, caddy, range, putter, club, course, game, fun, gentlemen, ball, minigolf, tee`,
  "ruhr": ``,
  "pink": `cute, pretty, sweet, girl, woman, gum`,
  "gold": `luxury, wealth, assets, fancy, beautiful, best, champion, success, jewelry, bling, valuable, precious`,
  "sexy": `hot, attractive, `,
  "pics": `photos, camera, post, social, media, pictures, image, flick, film, photograph`,
  "luxe": `wealth, upper, assets, luxury, fancy, gold, rich, money, elegant, swank, glam`,
  "taxi": `taxi, uber, ride, transport, cab, vehicle, rental, fare, bus, ride`,
  "camp": `forest, nature, hike, fun, trek, family, lodge, cabin, woods`,
  "haus": `home, house, casa, family, company, patio, together`,
  "gift": `present, give, love, charity, donation, christmas`,
  "menu": `restaurant, food, choice, cafe, bakery, serve, carte, meal, recipe, chef`,
  "surf": `web, search, seek, content, site, ocean, surfing`,
  "toys": `play, children, kids, fun, happy, gifts, presents`,
  "fish": `ocean, seafood, swim, pescatarian, fishing, sport`,
  "rent": `house, money, lease, apartment, car, cash`,
  "film": `movie, cinema, flick, theater, animation, drama, show, screen, los angeles, camera, video, art`,
  "town": `suburbs, people, together, villa, local, home, village, metro `,
  "desi": `indian, urdu, holi, food, curry, dance, mumbai, samosa, bollywood, brown, masala, punjab, `,
  "fail": `lose, funny, flunk, flop, fault, fall, recall, defect, break`,
  "gent": `men, gentlemen, fancy, luxury, clubhouse`,
  "tube": `tv, watch, entertain, youtube, screen`,
  "moda": `modern, design, art,`,
  "vote": `election, president, campaign, america, democracy, congress, ratify, candidate, run`,
  "bank": `interest, credit, debit, atm, money, cash, savings, invest, loan`,
  "lgbt": `gay, rainbow, colorful, lesbians, transgender, trans, safe`,
  "game": `fun, play, video, happy, family, friends, win, phone, app`,
  "army": `defense, service, military, soldiers, fight, usa, america, navy, infantry, vets, veterans, weapons, armed, protect, patriot`,
  "rest": `relax, holiday, heal, sleep, relief, peace, death`,
  "limo": `assests, wealth, fancy, rich, money, luxury, swank, transport, taxi, cab, `,
  "diet": `health, fitness, green, body, food, nutrition`,
  "baby": `maternity, newborn, mom, cute, prenatal, pregnant, child, infant, family, toddler`,
  "fans": `cool, chill, cheer, support, spectators, sports, celebtriy, paparazzi, team, crowd, audience, public, sports, performance`,
  "sarl": ``,
  "navy": `military, soldiers,service, defense, army, patriot, america, usa, ocean, boat, sail, forces, vets, veterans, seal, war, naval, submarines, sailor, nautical, blue, marine, weapons, military, protect`,
  "reit": `investment, bank, interest, capital, market, stock, credit`,
  "ltda": ``,
  "qpon": `coupon, save, buy, store,sale, deals, voucher, discount, free, shop, customers, gift`,
  "auto": `car, insurance, sedan, suv, tire, transport, vehicle, automobile, rent, buy, drive, motorbike, robot, automation, machine, motor`,
  "voto": ``,
  "cars": `lot, truck, sedan, suv, tire, insurance, car, transport, vehicle, automobile, rent, buy, drive, motorbike, robot, automation, machine, motor`,
  "rich": `value, money, luxury, investment, affluence, capital, estate, assets, wealth, secure, success, finance`,
  "сайт": ``,
  "дети": ``,
  "space": `station, houston, universe, moon, place, location, event, performance, set, spot, stars, physics, astronomy, dark matter, cosmos, aliens, spaceship, astronaut, gravity, earth, sun, plants, cosmos`,
  "store": `shop, customers, buy, coupon, sell, sale, cashier, storage, keep, depot, stock, memory, grocery, market, money, mall, retail, outlet, merchant, business, bazaar, trade`,
  "cloud": `sky, fluffy, cute, white, high, storage, technology, memory`,
  "world": `earth, explore, together, universal, ocean, planet, nature, green, environment, location, travel, geography, cultures, global, humans, universe, international, global, public, share, charity, continent, country, sphere, foreign`,
  "tokyo": `japan, cute, japanese, nipponese, sushi, ramen, geisha, travel`,
  "rocks": `mountain, stone, gems, jewels, minerals, earth, awesome, great, sand, music, gnarly, amazing`,
  "today": `news, update, now, stat, evening, modern, current, contemporary, evening, present, time, technology, innovation`,
  "email": `write, inbox, recieve, login, send, letter, electronic, mail, text, username, fax, address, send, newsletter, spam, sms, gmail,`,
  "group": `together, people, class, family, team, friends, community, organization, band, forum, crowd,`,
  "media": `technology, print, multimedia, press, news, television, newspaper, journalism, blog, print, information, art, film, report, movie, social `,
  "click": `mouse, choose, computer, technology,`,
  "trade": `money, stock, market, deal, swap, barter, sell, merchandise, import, export, sale`,
  "press": `news, media, newsletter, today, information, journalism, report, printing, speech, paper, coverage, publish, column,`,
  "ninja": `jedi, japan, ninjutsu, hardcore, samurai, weapons, kungfu, asia, sushi, ramen, intense, cool, parkour, swords, awesome, dojo, hero, super`,
  "koeln": ``,
  "party": `holiday, club, music, dance, drinks, alcohol, fun, colorful, friends, vacation, play, campaign, politics, celebrate, event`,
  "paris": `france, french, eiffel, europe, travel, parisian, louvre, art, culture`,
  "video": `watch, movie, flix, film, camera, storage,`,
  "works": `job, projects, employee, search, excercise, union, labor, profession, career, occupation, profile, portfolio, boss`,
  "photo": `picture, pic, post, media, share, likes, camera, portrait, image, polaroid, footage`,
  "house": `casa, patio, home, family, invite, safe, security, design, interior, love, welcome, live, together, resident, rent, bedroom, apartment, condo, room, villa, village, shack, cabin, loft, abode, cottage, palace, flat`,
  "games": `video, play, friends, fun, children, kids, contest, sports, team, championship, rance, athletes, win`,
  "swiss": `europe, chocolate, cheese, army, knife, skiing, mountains, alpine,`,
  "guide": `counsel, instruction, advise, scout, show, manual, handbook, bible, jesus, religion, light, shepherd, navigation, gps, directory, planner,tour, kit, textbook, directory, instruct, orientation, manage`,
  "earth": `world, international, planet, love, ocean, environment, green, climate`,
  "coach": `counsel, sports, champion, mentor, support, horse, carriage, guide`,
  "vegas": `gamble, fun, lights, sin, city, party, celebrate, nevada, las vegas,`,
  "legal": `lawyer, law, invest, attorney, firm, representative, prosecutor, crime, bail`,
  "wales": `scotland, scottish`,
  "tools": `fix, kit, resources, equipment, materials, framework, aids, devices, gears, build`,
  "style": `clothes, trendy, design, slay, modern, classy, vogue, fashion, model boutique, couture`,
  "money": `retail, money, interest, credit, bank, atm, fund, business, sell, buy, green, cash, bank, invest, stock, stock, market, deal, swap, barter, sell, merchandise, import, export, sale, interest, credit, debit, atm, cash, savings, invest, loan`,
  "homes": `casa, patio, home, family, invite, safe, security, design, interior, love, welcome, live, together, resident, rent, bedroom, apartment, condo, room, villa, village, shack, cabin, loft, abode, cottage, palace, flat`,
  "tours": `guide, show, travel, museum,learn, explore, trips, journey, voyage, visit, gallery, art`,
  "codes": `app, program, encrypt, computer, numbers, identification, security, discounts, coupon, deal, `,
  "watch": `movie, film, theater, perform, show, stage, play, television, time, observe, look`,
  "miami": `florida, tropical, vacation, orlando, beach, jacksonville, tampa`,
  "sport": `team, baseball, fishing, hobby, champion, game, athlete, race, compete, coach, soccer, basketball, football, exercise, gym, play`,
  "deals": `sale, buy, shop, coupon, discount`,
  "adult": `mature, sexy, xxx, porn`,
  "jetzt": ``,
  "dance": `club, fun, celebrate, happy, music, performance, moves, choreographer, show `,
  "sucks": `bad, sad, lose, fail,`,
  "cymru": ``,
  "pizza": `cheese, pie, pepperoni, pizzeria, italian`,
  "tirol": ``,
  "solar": `sun, power, alternative, yellow, heat, renewable, sol`,
  "promo": `promotion, coupon, discount, sweepstake, advertisement`,
  "faith": `christianity, bhuddhism, judaism, dogma, spiritual, organization, religion, jesus, love, church, synagogue, mosque, islam, buddha, temple, god, allah, bible, quran, torah, goddess, mohammed, mohamed, christian`,
  "parts": `car, fix, broken, auto, vehicle, tires, engine`,
  "cards": `play, game, postcards, identification, sentiment, sympathy, get well, kind, sweet, greeting, thank you, business`,
  "audio": `podcast, music, av, songs, cd, mp3, sound, recording, audiobook, voice, track,`,
  "green": `alternative, environment, health, color, leaves, nature, weed, garden, forest, woods, envy, eco, eco-friendly, ecology`,
  "shoes": `feet, shoe, sneakers, dress shoes, sandals, boots, soles, heels, cleats, sport`,
  "black": `african, ebony, classy, classic, supreme, africa, dark, night, afro, ink, pen`,
  "irish": `patrick, ireland, european, `,
  "loans": `interest, credit, money, bank, give, finance, invest, mortgage, len, payment, debt, fund, borrow, pay`,
  "place": `spot, location, home, event, position, property`,
  "build": `create, make, expand, construction, house`,
  "cheap": `discount, affordable, economical, coupon,`,
  "gifts": `give, charity, present, exchange, toys, jewelry, christmas`,
  "glass": `wine, crystal, bottle, windshield, vase, drink, water, fibreglass`,
  "poker": `gamble, money, fire, chips, night, play, games,`,
  "movie": `watch, film, screening, theater, video, screenwriter, scene`,
  "salon": `hair, nails, woman, shop, beauty, lips, wax, eyebrows, sugar wax, drybar, blowdry, extensions, weave, braids`,
  "horse": `equestrian, pony, stallion, jockey, racehorse, showhorse, farm, mustand, riding, horseback riding`,
  "archi": `architect`,
  "radio": `music, songs, fm, am, podcast, talkshow`,
  "actor": `film, movie, character, celebrity, thespian, theater, rpg, star, actress, cast, performer, scene, role, artist`,
  "vodka": `drink, liquor, russia, russian, bar, booze, alcohol, spirits, brew `,
  "lease": `rent, money, house, car, contract, tenant`,
  "gives": `charity, give, charity, present, exchange, toys, jewelry, christmas, loan, present, donation, christmas, goodwill `,
  "rehab": `therapy, alcoholism,health, detox, fitness, care, program, psychiatric, addiction, counseling `,
  "bible": `religion, faith, christianity, christian, jesus, church, word,`,
  "study": `school, education, books, textbook, course, university, secondary, institution, primary, college, technical, intern, public, private, charter, apprenticeship, attendance,train, children, school, education, learn, classes, enroll, academic, academia, degree, tuition, diploma, research, scholar, advocacy, lessons, grade, knowledge, course,study, student, teacher, instruction, train, curriculum, educators, teach, university `,
  "bingo": `play, game, senior, yes, jackpot, lottery, gotcha`,
  "gripe": `complain, petition, feedback,`,
  "reise": ``,
  "tires": `car, truck, wheels,`,
  "tatar": `tots, potatoes`,
  "kyoto": `japan,`,
  "osaka": `japan,`,
  "rodeo": `texas, bull, clown, cowboy`,
  "rugby": `sport, competition, netball`,
  "boats": `sail, ocean, travel, voyage, sailor, travel, luxury, vacation`,
  "autos": `car, automobile, vehicle, tires, truck, taxi`,
  "forex": `foreign, exchange, trade, investment, stock, import, export`,
  "lotto": `lottery, win, cash, gamble, sweepstake, casino, roulette, raffle, ticket`,
  "online": `web, website, internet, site, virtual, electronic, cyber, network, connection, net, app, search, surf`,
  "design": `art, interior, colors, portfolio, create, architecture, style, fashion, drawing, build, model, decoration`,
  "agency": `bureau, firm, organization, office, authority, department, company, corporation, administration, council, board, branch, unit,institution, foundation, establishment`,
  "studio": `art, music, create, build,`,
  "global": `earth, explore, together, universal, ocean, planet, nature, green, environment, location, travel, geography, cultures, global, humans, universe, international, global, public, share, charity, continent, country, sphere, foreign,`,
  "london": `united kingdom, english, travel, explore, city`,
  "berlin": `germany, german, city, travel, art, techno, club`,
  "center": `middle, organization,`,
  "expert": `advice, consultant, professional, expert, specialist, skilled, master, business, internship, technology, tech, credentials, career, trained, coaching, specialized, occupation, vocation, work, employment, employee, consultant, employer, career, industry, admin, management, trades, jobs, labor, talent, prodigy, mentor,`,
  "bayern": ``,
  "events": `show, perform, calendar, music, go out, city, party, club, drink, dance, happy, fun, venue, festival, gala, parade, carnival, celebrate,, conference, occasion`,
  "church": `faith, religion, christian, jesus, bible, pray`,
  "social": `media, blog, friendly, welfare, party, talk, connect, community`,
  "market": `bazaar, buy, sell, trade, stock, business,`,
  "africa": `ebony, countinent, brown, safari, journey, travel, world`,
  "stream": `video, watch, movies, swim, youtube`,
  "photos": `pictures, photos, post, media, share, camera`,
  "family": `friends, love, home, children, kids, wife, husband`,
  "moscow": `russia, city, russian,`,
  "coffee": `cafe, caffeine, morning, breakfast, beans, starbucks, barista, espresso, latte, mocha`,
  "review": `feedback, complain, critique, survey, follow up, evaluation, revision`,
  "webcam": `skype, chat, camera, video, photo, computer`,
  "school": `education, learn, class, students, university, textbook, teacher, grades,`,
  "boston": `east coast, pie, cheescake`,
  "direct": `stat, immediate, send, target`,
  "energy": `drinks, excite, batteries, charge, solar, thermal, geothermal, hydro`,
  "health": `fitness, green, fit, athlete, medical, medicine, hospital, pharmacy, care, insurance, doctors, physician, cancer, life, happy, disease, wholesome`,
  "lawyer": `law, prosecute, attorney, firm, representative`,
  "estate": `real estate, invest, asset, land, inheritance, property`,
  "clinic": `hospital, urgent care, health, sick, checkup, medical, exam, doctor`,
  "sydney": `australia`,
  "dental": `teeth, orthodontist, braces, smile, dentist, enamel`,
  "tattoo": `permanent, art, ink, mark, henna,`,
  "racing": `compete, sport, ride, horse, racecar, nascar`,
  "report": `news, journalism, blog, paper, study, write, document, review, information, opinion`,
  "vision": `idea, view, see, glasses, see, health, visual, imagination, dreams, ideals, philosophy, dogma, ideas, view, perspective, pov, outlook`,
  "repair": `fix, mend, broken, maintain, restore, refurbish`,
  "quebec": `canada, french, montreal`,
  "kaufen": ``,
  "nagoya": ``,
  "doctor": `medicine, physician, health, doc, surgeon, dentist, psychiatrist, medical, practitioner, hospital, medic, clinician, clinic, ambulance, healthcare, pediatrician, dermatologist`,
  "casino": `gamble, poker, blackjack, vegas, cards, game`,
  "supply": `demand, manufacture, economy`,
  "credit": `score, loan, bank, interest`,
  "insure": `insurance, agree`,
  "reisen": ``,
  "gratis": ``,
  "camera": `photo, picture, film, webcam, cam, photography, image`,
  "joburg": ``,
  "dating": `girlfriend, tinder, boyfriend, love, cute, relationship`,
  "soccer": `play, sport, fun, ball`,
  "schule": `school`,
  "claims": `insurance`,
  "degree": `school, university, diploma, study, college, major`,
  "voyage": `travel, journey, sail, boat, sea, ocean, vacation`,
  "garden": `green, vegetables, veggie, healthy, flowers`,
  "futbol": `football,sport`,
  "durban": ``,
  "realty": `real estate`,
  "taipei": `taiwan, china`,
  "alsace": ``,
  "tienda": ``,
  "condos": `apartment, flat`,
  "villas": `homes, house`,
  "ryukyu": ``,
  "tennis": `ping pong`,
  "hockey": ``,
  "viajes": ``,
  "career": `occupation, work, job, school, university, employee`,
  "physio": `physiology, anatomy, workout, exercise`,
  "maison": `french, house, home, condo`,
  "luxury": `wealth, upper, assets, luxury, fancy, gold, rich, money, elegant, swank, glam`,
  "hiphop": `rap, trap`,
  "broker": `agent, trader, dealer, banker, salesman, representive, realtor, facilitate`,
  "juegos": ``,
  "voting": `election, ballot, candidate, politcs, bill, poll`,
  "madrid": `spain`,
  "yachts": `boat, vacation, wealthy,sail, ocean`,
  "makeup": `beauty, salon, cosmetics, makeover, face,`,
  "москва": ``,
  "онлайн": ``,
  "website": `online, web, site, link, blog, web, internet, site, virtual, electronic, cyber, network, connection, net, app, search, surf`,
  "company": `tech, startups, business, firm, agency, biz, money, design, market, sell, buy, stocks, invest, wholesale, co`,
  "network": `web, website, internet, site, virtual, electronic, cyber, network, connection, net, app, search, surf`,
  "digital": `tech, applications, mobile, intelligence, gadgets, startups, science, innovate, engineering, entrepreneur, intelligence, artificial, robots, systems, devices computer, biotech, business, startup, service, saas, on, off, mobile, frontend, backend, design, tech, web, electronics, text, game, publish, ios, android, io, ai, mac, windows, application, program, software, coding, code, python, javascript, html, css, sql, database, security, developer,`,
  "realtor": `real estate, house, broker, property, agent, condo, tenant,`,
  "academy": `prep, school, education, books, textbook, course, university, secondary, institution, primary, college, technical, intern, public, private, charter, apprenticeship, attendance,train, children, school, education, learn, classes, enroll, academic, academia, degree, tuition, diploma, research, scholar, advocacy, lessons, grade, knowledge, course,study, student, teacher, instruction, train, curriculum, educators, teach, university`,
  "systems": `security, computer, network`,
  "support": `coach, counsel`,
  "wedding": ``,
  "hamburg": ``,
  "reviews": ``,
  "gallery": ``,
  "science": ``,
  "capital": ``,
  "rentals": ``,
  "fitness": ``,
  "cologne": ``,
  "fashion": ``,
  "finance": ``,
  "careers": ``,
  "express": ``,
  "kitchen": ``,
  "domains": ``,
  "forsale": ``,
  "recipes": ``,
  "okinawa": ``,
  "limited": ``,
  "holiday": ``,
  "auction": ``,
  "hosting": ``,
  "college": ``,
  "singles": ``,
  "dentist": ``,
  "jewelry": ``,
  "exposed": ``,
  "coupons": ``,
  "flights": ``,
  "cricket": ``,
  "cruises": ``,
  "florist": ``,
  "charity": ``,
  "organic": ``,
  "courses": ``,
  "surgery": ``,
  "cooking": ``,
  "corsica": ``,
  "fishing": ``,
  "flowers": ``,
  "theater": ``,
  "trading": ``,
  "shiksha": ``,
  "guitars": ``,
  "country": ``,
  "tickets": ``,
  "markets": ``,
  "storage": ``,
  "abogado": ``,
  "hoteles": ``,
  "whoswho": ``,
  "theatre": ``,
  "services": ``,
  "business": ``,
  "training": ``,
  "software": ``,
  "download": ``,
  "ventures": ``,
  "clothing": ``,
  "exchange": ``,
  "istanbul": ``,
  "boutique": ``,
  "pictures": ``,
  "partners": ``,
  "brussels": ``,
  "attorney": ``,
  "graphics": ``,
  "shopping": ``,
  "delivery": ``,
  "lighting": ``,
  "holdings": ``,
  "computer": ``,
  "capetown": ``,
  "football": ``,
  "yokohama": ``,
  "discount": ``,
  "saarland": ``,
  "builders": ``,
  "catering": ``,
  "engineer": ``,
  "property": ``,
  "mortgage": ``,
  "supplies": ``,
  "bargains": ``,
  "plumbing": ``,
  "diamonds": ``,
  "cleaning": ``,
  "feedback": ``,
  "hospital": ``,
  "democrat": ``,
  "observer": ``,
  "memorial": ``,
  "abudhabi": ``,
  "airforce": ``,
  "pharmacy": ``,
  "security": ``,
  "broadway": ``,
  "solutions": ``,
  "amsterdam": ``,
  "education": ``,
  "marketing": ``,
  "directory": ``,
  "community": ``,
  "institute": ``,
  "melbourne": ``,
  "barcelona": ``,
  "financial": ``,
  "equipment": ``,
  "vacations": ``,
  "furniture": ``,
  "christmas": ``,
  "insurance": ``,
  "stockholm": ``,
  "technology": ``,
  "consulting": ``,
  "foundation": ``,
  "properties": ``,
  "management": ``,
  "healthcare": ``,
  "restaurant": ``,
  "university": ``,
  "immobilien": ``,
  "vlaanderen": ``,
  "accountant": ``,
  "industries": ``,
  "apartments": ``,
  "associates": ``,
  "creditcard": ``,
  "republican": ``,
  "protection": ``,
  "photography": ``,
  "productions": ``,
  "engineering": ``,
  "enterprises": ``,
  "investments": ``,
  "contractors": ``,
  "accountants": ``,
  "blackfriday": ``,
  "creditunion": ``,
  "motorcycles": ``,
  "construction": ``,
  "versicherung": ``,
  "international": ``,
  "网址": ``,
  "在线": ``,
  "公司": ``,
  "手机": ``,
  "商标": ``,
  "网络": ``,
  "商城": ``,
  "我爱你": ``,
  "中文网": ``,
  "닷컴": ``,
  "网店": ``,
  "コム": ``,
  "移动": ``,
  "קום": ``,
  "信息": ``,
  "集团": ``,
  "购物": ``,
  "企业": ``,
  "닷넷": ``,
  "みんな": ``,
  "世界": ``,
  "شبكة": ``,
  "商店": ``,
  "بازار": ``,
  "网站": ``,
  "موقع": ``,
  "机构": ``,
  "游戏": ``,
  "ストア": ``,
  "广东": ``,
  "娱乐": ``,
  "セール": ``,
  "招聘": ``,
  "佛山": ``,
  "संगठन": ``,
  "餐厅": ``,
  "家電": ``,
  "クラウド": ``,
  "食品": ``,
  "八卦": ``,
  "書籍": ``,
  "ac": `academic, academy`,
  "ad": `advert, marketing, agency, `,
  "ag": `agriculture, farm, harvest, german`, // germany's llc or inc equivalent: "aktiengesellschaft"
  "as": `estonia`, // estonia's llc or inc equivalent: "akciová společnost"; as {preposition}, as a {noun}, as {adverb}
  "at": ``,
  "be": `become`, // youtu.be
  "by": ``, // fly {by}
  "cc": `christian, christ, jesus, church, college, community college, community`,
  "cd": `cd, music, tunes, listen, `,
  "ch": `church, jesus, christian, christ, `,
  "ck": ``,
  "dj": `dj, club, music, clubbing, party, `,
  "es": ``, // beach{es}
  "fi": `hifi, audio, recording, `,
  "gl": `galic, galicia, greenland, google`,
  "gg": `gaming, gambling, poker, casino, `,
  "im": `instant messaging, texting, text, sms, chat, online, `,
  "is": ``, // is {adj/adv}
  "ir": `iran`,
  "it": `italy, do, act, `, // {verb} it
  "je": `dutch, french, jersey, i, `,
  "la": `los angeles, latin, `,
  "li": `long island`,
  "lv": `love`,
  "ly": ``, // {noun/adj}ly
  "md": `doctor, medical, medicine, hospital, nursing, medschool, mcat, `,
  "me": `montenegro, middle east, `,
  "mn": `mongolia, minnesota, `,
  "ms": `microsoft`,
  "mu": `music, song, musical, playing, acoustic, vocal, rock, pop music, rap, performance art, `,
  "ni": ``,
  "nu": `new, nude`,
  "pr": `public relations, marketing, human resources, press release, press`,
  "rs": ``, // {blogge}rs
  "sc": `source`,
  "sh": `china`,
  "si": `slovenia, yes`,
  "sr": `senior, old, respectable, `,
  "st": `street`,
  "tc": `turk`,
  "tm": `trademark, copyright, slogan, trade, mark, logo, `,
  "to": `toronto, turino, `, //
  "tv": `television, italy`,
  "vc": `venture capital, vacation, casino, `,
  "vg": `video games, `,
  "vu": `view`,
  "ws": `website`,
  "in": `india, internet, `, // {noun} in

  "ca": `canada, california, `,
  "ae": ``,
  "af": ``,
  "al": ``,
  "ao": ``,
  "aq": ``,
  "ar": ``,
  "au": ``,
  "aw": ``,
  "ax": ``,
  "az": ``,
  "ba": ``,
  "bb": ``,
  "bd": ``,
  "bf": ``,
  "bg": ``,
  "bh": ``,
  "bi": ``,
  "bj": ``,
  "bm": ``,
  "bn": ``,
  "bo": ``,
  "br": ``,
  "bs": ``,
  "bt": ``,
  "bv": ``,
  "bw": ``,
  "bz": ``,
  "cf": ``,
  "cg": ``,
  "ci": ``,
  "cl": ``,
  "cm": ``,
  "cn": ``,
  "cr": ``,
  "cu": ``,
  "cv": ``,
  "cw": ``,
  "cx": ``,
  "cy": ``,
  "cz": ``,
  "de": ``,
  "dk": ``,
  "dm": ``,
  "do": ``,
  "dz": ``,
  "ec": ``,
  "ee": ``,
  "eg": ``,
  "er": ``,
  "et": ``,
  "eu": ``,
  "fj": ``,
  "fk": ``,
  "fo": ``,
  "fr": ``,
  "ga": ``,
  "gb": ``,
  "gd": ``,
  "ge": ``,
  "gf": ``,
  "gh": ``,
  "gi": ``,
  "gm": ``,
  "gn": ``,
  "gp": ``,
  "gq": ``,
  "gr": ``,
  "gs": ``,
  "gt": ``,
  "gu": ``,
  "gw": ``,
  "gy": ``,
  "hk": ``,
  "hm": ``,
  "hn": ``,
  "hr": ``,
  "ht": ``,
  "hu": ``,
  "id": ``,
  "ie": ``,
  "il": ``,
  "iq": ``,
  "jm": ``,
  "jo": ``,
  "jp": ``,
  "ke": ``,
  "kg": ``,
  "kh": ``,
  "ki": ``,
  "km": ``,
  "kn": ``,
  "kp": ``,
  "kr": ``,
  "kw": ``,
  "ky": ``,
  "kz": ``,
  "lb": ``,
  "lc": ``,
  "lk": ``,
  "lr": ``,
  "ls": ``,
  "lt": ``,
  "lu": ``,
  "ma": ``,
  "mc": ``,
  "mg": ``,
  "mh": ``,
  "mk": ``,
  "ml": ``,
  "mm": ``,
  "mo": ``,
  "mp": ``,
  "mq": ``,
  "mr": ``,
  "mt": ``,
  "mv": ``,
  "mw": ``,
  "mx": ``,
  "my": ``,
  "mz": ``,
  "na": ``,
  "nc": ``,
  "ne": ``,
  "nf": ``,
  "ng": ``,
  "nl": ``,
  "no": ``,
  "np": ``,
  "nr": ``,
  "nz": ``,
  "om": ``,
  "pa": ``,
  "pe": ``,
  "pf": ``,
  "pg": ``,
  "ph": ``,
  "pk": ``,
  "pl": ``,
  "pm": ``,
  "pn": ``,
  "ps": ``,
  "pt": ``,
  "pw": ``,
  "py": ``,
  "qa": ``,
  "re": ``,
  "ro": ``,
  "ru": ``,
  "rw": ``,
  "sa": ``,
  "sb": ``,
  "sd": ``,
  "se": ``,
  "sg": ``,
  "sj": ``,
  "sk": ``,
  "sl": ``,
  "sm": ``,
  "sn": ``,
  "so": ``,
  "ss": ``,
  "su": ``,
  "sv": ``,
  "sx": ``,
  "sy": ``,
  "sz": ``,
  "td": ``,
  "tf": ``,
  "tg": ``,
  "th": ``,
  "tj": ``,
  "tk": ``,
  "tl": ``,
  "tn": ``,
  "tr": ``,
  "tt": ``,
  "tw": ``,
  "tz": ``,
  "ua": ``,
  "ug": ``,
  "uk": ``,
  "us": ``,
  "uy": ``,
  "uz": ``,
  "va": ``,
  "ve": ``,
  "vi": ``,
  "vn": ``,
  "wf": ``,
  "ye": ``,
  "yt": ``,
  "za": ``,
  "zm": ``,
  "zw": ``,


  "gdn": ``,

};
